package test;

import javafx.fxml.FXML;

import javafx.scene.chart.LineChart;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.control.TableView;

import javafx.scene.layout.GridPane;

import javafx.scene.layout.Pane;

public class sceneController {
	@FXML
	private AnchorPane AnchorPane;
	@FXML
	private TableView solarTable;
	@FXML
	private ToggleGroup solarone;
	@FXML
	private ToggleGroup solartwo;
	@FXML
	private ToggleGroup solarthree;
	@FXML
	private LineChart solarGraph;
	@FXML
	private ToggleGroup netmetering;
	@FXML
	private ToggleGroup ratesweek;
	@FXML
	private GridPane rateGrid;
	@FXML
	private CheckBox tieredRateCB;
	@FXML
	private CheckBox timeOfUseCB;
	@FXML
	private CheckBox criticalPeakCB;
	@FXML
	private CheckBox netGridNonSolarCB;
	@FXML
	private CheckBox netGridSolarCB;
	@FXML
	private Pane gridGraphPane;

	// Event Listener on Button.onMouseReleased
	@FXML
	public void showRatepayersGraph(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void aboutClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
