/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_RateReviewerProxy */

#ifndef _Included_application_RateReviewerProxy
#define _Included_application_RateReviewerProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_RateReviewerProxy
 * Method:    initInterface
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_application_RateReviewerProxy_initInterface
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
